export enum ProductErrorCodes {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_HAS_PRODUCTS = 'CATEGORY_HAS_PRODUCTS',
  INVALID_PRICE = 'INVALID_PRICE',
  INVALID_STOCK = 'INVALID_STOCK',
  IMPORT_FILE_TOO_LARGE = 'IMPORT_FILE_TOO_LARGE',
  IMPORT_TOO_MANY_ROWS = 'IMPORT_TOO_MANY_ROWS',
  IMPORT_INVALID_CSV = 'IMPORT_INVALID_CSV',
  EXPORT_FAILED = 'EXPORT_FAILED',
}